spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_security_test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true # sql을 이쁘게 format
    defer-datasource-initialization: true
logging:
  level:
    org.hibernate.SQL: debug # 바인딩 된 파라미터까지 볼 수 있다.