spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true # sql을 이쁘게 format
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug # 바인딩 된 파라미터까지 볼 수 있다.